### ISSUE TITLE
The Engine doesn't increment views field

### ISSUE THREAD

**Issue by adam-pl** [did/locomotive_view_counter#1]
The Wagon works fine :-)

The Engine doesn't increment the counter because of it has always `env['steam.live_editing']` value equal to `true`, even on production.

Should I force `env['steam.live_editing']` in production  to `false`?

**Comment by adam-pl** [comment]
I need to test opening page via domain instead of preview link.

**Comment by did** [comment]
that's right @adam-pl. It was done one purpose because we don't the view counter to be incremented when you're editing your page.
